spring:
  profiles:
    active:
    - dev
---
Spring:
  profiles: dev #开发环境
  application: 
    name: linservicecloud-config-haorenlin-dev    
---
Spring:
  profiles: test #测试环境
  application: 
    name: linservicecloud-config-haorenlin-test    
